### ISSUE TITLE
[Localized Vacuum Cleaner] On reset last position is mark as cleaned

### ISSUE THREAD

**Issue by javizqh** [JdeRobot/RoboticsAcademy#2551] opened 2024-06-05 11:18 UTC
When reseting the excercise the last point will remain.

Here is a trace of console logs to see what is happening:

- At the top is the last position of the previous iteration
- Reset
- On the first iteration the Specific js from the excercise tells the helper to draw in one position but in the helper the values received are from the last execution.

![image](https://github.com/JdeRobot/RoboticsAcademy/assets/124056014/147b9968-4d71-45e9-a7e8-b01725cf23d2)

Here is a branch with the modified files to test: https://github.com/javizqh/RoboticsAcademy/tree/issue-2551

**Comment by Apoorvgarg-creator** [comment] 2024-06-23 16:20
@javizqh Just to get clarity over the issue, The problem is that on resetting it is still giving you the last iteration position.
Where as it should be initial position

**Comment by javizqh** [comment] 2024-06-23 16:42
If it was the initial position it would be fine, preferably it shouldn't give a position from the last execution.

**Comment by Apoorvgarg-creator** [comment] 2024-06-23 17:03
> If it was the initial position it would be fine, preferably it shouldn't give a position from the last execution.

Thank you for the reply. working on the issue, So Sorry for the late view.

**Comment by Apoorvgarg-creator** [comment] 2024-06-23 17:34
<img width="1430" alt="Screenshot 2024-06-23 at 11 03 23 PM" src="https://github.com/JdeRobot/RoboticsAcademy/assets/57873504/3033a92d-9960-4f8d-8ba6-f6a1b6bc8796">

@javizqh From the above Screenshot, I wanted to ask in **vacuum_cleaner_loc_newmanager** 
The **SpecificVacuumCleaner** widget you uses is from **exercise/vacuum_cleaner_newmanager/SpecificVacuumCleaner**

**Comment by Apoorvgarg-creator** [comment] 2024-06-23 17:35
@javizqh Can you share me the solution you ran.

**Comment by Apoorvgarg-creator** [comment] 2024-06-23 17:38
> <img alt="Screenshot 2024-06-23 at 11 03 23 PM" width="1430" src="https://private-user-images.githubusercontent.com/57873504/342102848-3033a92d-9960-4f8d-8ba6-f6a1b6bc8796.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNjQzNjksIm5iZiI6MTcxOTE2NDA2OSwicGF0aCI6Ii81Nzg3MzUwNC8zNDIxMDI4NDgtMzAzM2E5MmQtOTk2MC00ZjhkLThiYTYtZjZhMWI2YmM4Nzk2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDE3MzQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyYjY3MjVjNGM1YTQzZDc2MDVlNzAwOTkxZTBiMGM4NDliMDc3NTk0OGQ4YzIyZTNkZjkxMGVhMDg3OWJkYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tLKaTkY-D3Pe8IKydPP7RiZQr1q79PEHMOcJoG2InBg">
> @javizqh From the above Screenshot, I wanted to ask in **vacuum_cleaner_loc_newmanager** The **SpecificVacuumCleaner** widget you uses is from **exercise/vacuum_cleaner_newmanager/SpecificVacuumCleaner**

I think the file needs to point at 
1. _**exercise/vacuum_cleaner__loc_newmanager/SpecificVacuumCleaner**_
2. _**exercise/vacuum_cleaner__loc_newmanager/BasicVacuumCleaner**_

**Comment by jmplaza** [comment] 2024-06-23 17:47
> @javizqh Can you share me the solution you ran.

I guess you can find it in the [RoboticsAcademy-solutions repo](https://github.com/JdeRobot/RoboticsAcademy-solutions) (private)

**Comment by Apoorvgarg-creator** [comment] 2024-06-23 17:52
> > @javizqh Can you share me the solution you ran.
> 
> I guess you can find it in the [RoboticsAcademy-solutions repo](https://github.com/JdeRobot/RoboticsAcademy-solutions) (private)

I ran the code from solution.py present in RoboticsAcademy-solutions repo for this particular exercise but got some error in the console.

**Comment by javizqh** [comment] 2024-06-23 18:49
Sorry, there is a PR open in the solutions repo with the new solution.

**Comment by jmplaza** [comment] 2024-06-23 21:58
Merged @javizqh

**Closed as completed** 2024-07-02 15:09 UTC
