### ISSUE TITLE
GZViewer not launching with Nvidia GPU Acceleration

### ISSUE THREAD

**Issue by ReyDoran** [JdeRobot/RoboticsAcademy#2356] opened 2023-12-11 16:38 UTC

**Comment by jmplaza** [comment] 2024-02-20 11:30
Gzviewer is launching and also the console window on the correspoding vnc DISPLAYs, but those displays show black screens. We have a problem with Nvidia GPU acceleration in ROS2 Humble RADIs. They work fine on ROS1-Noetic RADIs though.

**Comment by CDAM2020** [comment] 2024-07-16 14:57
When the GPU is integrated on CPU this error doesn't appear.

**Comment by dduro2020** [comment] 2024-07-23 07:49
I'm having the same issue, but I don't know what could have caused it, it used to work without any problems.

**Comment by jmplaza** [comment] 2024-07-23 08:06
With RoboticsBackend 4.6.3 @dduro2020 ?

**Comment by dduro2020** [comment] 2024-07-23 08:10
Yes, when I updated my fork to the latest commits it started to crash @jmplaza

**Comment by dduro2020** [comment] 2024-07-23 10:41
I noticed that the browser buttons don't update (the console does), you can launch the code (without seeing what's going on), but you can't stop it or restart it

**Comment by CDAM2020** [comment] 2024-07-23 15:06
Can you specify the steps to reproduce this error? I've tested on some exercises and this error didn't appear.

**Comment by dduro2020** [comment] 2024-07-23 16:21
I was just launching the script `sh scripts/develop_academy.sh -g` and opening the exercises, for some reason it solved itself, I attach a picture of how I saw the error (I think the problem was that some browser components were frozen)
![Captura desde 2024-07-23 18-14-31](https://github.com/user-attachments/assets/399a0c11-e732-453f-896b-be9c0330c417)

**Comment by jmplaza** [comment] 2024-07-23 16:50
That is an instruction for developers, and I'm not sure whether it is outdated or not. Please check this issue as a regular user, just launching properly the RoboticsBackend and using RoboticsAcademy from the browser.

**Comment by dduro2020** [comment] 2024-07-23 17:00
I've been trying it both ways and got the same result, but I mean that by launching it this way it has been magically fixed

**Comment by dduro2020** [comment] 2024-07-24 09:29
After verifying that I was launching the wrong user version, I close the issue to open another one specifically for launching it for developers

**Closed by dduro2020** 2024-07-24 09:29 UTC

**Comment by jmplaza** [comment] 2024-07-24 09:32
Glad to see that following the launching instructions at the Robotics Academy [User Guide ](https://jderobot.github.io/RoboticsAcademy/user_guide/) and using the latest RoboticsBackend (4.6.3) this problem is completeley solved!
