### ISSUE TITLE
Error messages in vnc views when changing world

### ISSUE THREAD

**Issue by dduro2020** [JdeRobot/RoboticsAcademy#2668] opened 2024-07-24 09:35 UTC
Changing the world of any exercise does not update the vnc views (also not working in unibotics with 4.6.4)

![Captura desde 2024-07-29 12-49-06](https://github.com/user-attachments/assets/60a50e9f-ef52-46dd-a1e9-e4d4fa3ce0f5)

**Comment by dduro2020** [comment] 2024-09-02 08:46
The vnc views now load correctly, but whenever you change an exercise world, apart from adding up errors from trying to finish processes that have already finished, you get an error when supposedly nothing has failed.

Here's a screenshot of the error message (just after it loads correctly, but it looks like a residual message that shouldn't appear)
![image](https://github.com/user-attachments/assets/d3143c88-7a4c-422a-ac4f-aa63211a077a)


First time changing the world:
![image](https://github.com/user-attachments/assets/54a08e18-369d-4242-af54-8c528be56d1c)

Second time (And each time you do it again, error messages are added up, which you will see again when the container is finished):
![image](https://github.com/user-attachments/assets/02a73134-32c2-4c09-ad3d-601c034dff01)

**Comment by javizqh** [comment] 2024-09-02 10:46
The error displayed to the user does not matter because it is caused by the Gazebo viewer loading a couple of seconds slower than the console and it is solved after a 2 or 3 seconds

**Comment by javizqh** [comment] 2024-09-02 11:14
I'm going to close this issue and open it in the Manager repository

**Closed as completed by javizqh** 2024-09-02 11:14 UTC
