### ISSUE TITLE
[Global Navigation] Runtime error when running example code

### ISSUE THREAD

**Issue by pawanw17** [JdeRobot/RoboticsAcademy#2535] opened 2024-05-22 12:25 UTC
When trying to run the solution code: https://github.com/JdeRobot/RoboticsAcademy-solutions/blob/master/solutions/global_navigation/basic_Global_Navigation.py
```
root@e14a8c465c4c:/# HAL-Nodes Thread Started
World : [-108.91089108910893, 1.6248839368616643]
Error in shared image add TypeError("'NoneType' object does not support item assignment")
Traceback (most recent call last):
  File "/workspace/code/shared/image.py", line 180, in add
    self.shm_buf_1[:] = image.tobytes()
TypeError: 'NoneType' object does not support item assignment
``` 

![image](https://github.com/JdeRobot/RoboticsAcademy/assets/40732709/a08e5ea3-3046-4264-81d8-b024898c1f70)

**Comment by javizqh** [comment] 2024-06-03 08:59
Are you able to reproduce this bug? I am not able to do so

**Comment by javizqh** [comment] 2024-07-03 14:36
Can you reproduce this in the new 4.6.1 RB? @pawanw17

**Comment by dduro2020** [comment] 2024-07-10 12:10
I've been trying this solution and I can't reproduce the issue
. But with the solution https://github.com/JdeRobot/RoboticsAcademy-solutions/blob/master/solutions/global_navigation/Global_Navigation.py I get a similar error message:
```bash
Error in shared image add IndexError('mmap slice assigment is wrong size')
Traceback (most recent call last):
  File "/workspace/code/shared/image.py", line 156, in add
    self.shm_buf_2[:] = image.tobytes()
IndexError: mmap slice assigment is wrong size
```

![Captura desde 2024-07-10 14-08-30](https://github.com/JdeRobot/RoboticsAcademy/assets/90764701/0703ba5f-3d4a-431a-99dc-511078d61f29)

**Comment by javizqh** [comment] 2024-08-02 15:16
This can be closed as this issue cannot be reproduced any more.

**Closed as completed by javizqh** 2024-08-02 15:16 UTC
